[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "tinygrad"
version = "0.1.0"
description = "A simple module that implements automatic gradient computation"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "RaÃºl Barba Rojas", email = "barbarojasraul@gmail.com"}
]
license = "MIT"
keywords = ["autograd", "grad", "backpropagation", "neural networks"]
dependencies = []

[project.optional-dependencies]
dev = []

[tool.hatch.build.targets.wheel]
packages = ["src/tinygrad"]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
